<?php include 'header.php' ?>
<div class="container">
	<div class="row">
		<h3 class="terms-use"> TERMS OF USE</h3>
		<div class="col-md-12">
			<p>Please read the below mentioned terms and conditions very carefully as the right(s) of every individual user to use this website is subject to acceptance of these terms and conditions.</p>
			<p>The present terms of use and privacy policy or any other policy that is mentioned on this website constitute an agreement between tabcii.com and the user of this website. The term “user” shall include the customer or service user and the logistic service provider. A service user or a logistic service provider can be a person, company, firm or any artificial person who is competent to enter into a legally binding agreement. These terms and conditions shall be binding on all, for the use of this website which shall define the rights, duties and limitations of all the users.</p>
			<p>The users of this website are either the service users or the logistic service providers  who accept/ acknowledge that this website shall be used as a platform for them to offer and avail services in accordance to the terms of use of this website and allow online payments, display of advertisements and modification in terms of use and policies by tabcii.com whenever required.</p>
			<p>If the user does not agree or are not willing to accept and follow these policies then  the user is requested not to proceed further or avail any of the services of this website.</p>
		</div>
		
		<div class="col-md-12">
			<h3 class="terms-use"> INTRODUCTION</h3>
			<p>www.tabcii.com is an E-commerce portal which is a platform for the logistic service providers to offer their services and service users to avail the benefit of the services offered to them. This website can only be used by the user if they accept these terms and conditions without any modification, however tabcii.com has complete authority and right to modify or change any or all of its terms and conditions for which  the company as per its sole discretion may or may not  provide you with a notice and  put it on its website which shall be the sole discretion of the company. tabcii.com possesses complete and absolute authority to stopor  disallow any person  from availing the facility of this website or use this website or  get registered on this website.</p>
		</div>
		
		<div class="col-md-12">
			<h2>USER ACCOUNT</h2>
			<h3 class="terms-use"> LICENSE TO USERS</h3>
			<p>tabcii.com allows the users of this website a non exclusive, revocable license to avail the services of this website subject to  the condition that  the user shall follow these terms and conditions and shall not go against or do any act that is  derogatory, harmful, offensive, injurious, or destructive for tabcii.com and in case any such act is done by any  user then  tabcii.com has full authority to revoke the customers  license to use this website without any prior notice..</p>
			<h3 class="terms-use"> USER ELIGIBILITY </h3>
			<p>The user of this website shall be above 18 years of age and in case the user is an artificial person/legal person which comprises of a company, firm, LLP etc.   then the same shall be a registered legal entity competent by law to enter into a valid contract. The user acknowledges that whatever information is provided by the user to tabcii.com at the time of registration is correct/true and that if in future it is found by tabcii.com that any  information provided by the user of this website is false, incorrect then  the account of that user shall be terminated without any notice or warning.</p>
			<p>To create an account on tabcii.com for the purpose of availing its facilities the user needs to fill a registration form which will ask him about his personal information which is mandatory to get registered on this website and by that  the user will get a user name and a password for easy access and use of this website</p>
			<p>tabcii.comensuresthe user that it will take good care of the user’s personal information but we expect the same from the user as well which means that the user should also take precautions and not share their personal information in regard to their user account on this website and shall never share your password with any one and it shall be their sole responsibility of the user to take care  of any activity that is done on or through the account of the user and the user shall be solely  responsible for any loss or damage which might take place due to any activity done by the user’s account either by user himself or by any unauthorized person. If the user feel at any point of time that there is any breach of security or any unauthorized use of user’s Account is being done, then the user shall inform tabcii.com so that appropriate steps can be taken to stop such act.  </p>
			<p>The user shall acknowledge and agree that he shall abide with the following conditions:</p>
			<p>(a) The user shall not copy, distribute, amend or modify any part or content of this website without the prior written consent of tabcii.com.</p>
			<p>(b)	The user shall provide true, correct, recent and full information while creating a user Account and the user shall update such information from time to time as it changes during the term of this Agreement.</p>
			<p>(c)	The user of this website shall not in any way use any technology or any means to either destroy, damage or affect in a negative manner the infrastructure of the website. The user shall not send fake, false or incorrect requests, offers or bids in any form. If any such thing is done then  tabcii.com  has complete authority to terminate the account of that user without giving any notice.</p>
			<p>(d)	The user of this website agrees to this condition that they  will never use the information available on this website which includes the personal information of the customers given to the logistic service providers  or the information  provided to the customers in   relation to the logistic service provider in any way which is wrong,  illegal, unethical or immoral and if anyone is found doing such an act then legal action will be taken against that person and his user account shall be terminated without giving any prior notice.</p>
			<div class="col-md-12">
				<h3 class="terms-use"> USER CONDUCT </h3>
				<p>The user of this website shall not do any illegal act which is against law or in any way harmful or damaging to any person associated  with this website. The user shall not defame or abuse or misuse the contents of this website. The user shall not violate any of the terms, conditions and policies mentioned herein or anywhere else on this website. The user shall abide by the following conditions which are:</p>
				<p>(a)	The user of this website shall never publish any personal information such as name, email address, phone number, password, account information, credit card number, home address or other contact information of any person without their knowledge and without consent.The user of this websiteshallnever publish any data, content or work of any person which is protected by copyright or is a trade secret of  that person without the prior permission of that person and of tabcii.com in writing.</p>
				<p>(b)	The user shall never publish or put any pornographic/ distressing/ hateful/ illegal/ obscene/ defamatory/ libelous/ insulting/ bullying/ prejudicing / racial/ ethically offensive content, image, data or video, such an act will be considered as a criminal offense and strict action will be taken against any such person who shall be found guilty of committing such an offence.</p>
				<p>(c)	The user shall never publish any data or content which may intent   to threaten/ track/ defame/ abuse anyone for any reason on the basis of age, gender, disability, ethnicity, sexual orientation, race, or religion;</p>
				<p>(d)	The user of this website shall never do any such act with a purpose to damage another user's computer or  user account or send any junk mails, spam, advertisement or any such content that does not have any link with the business of this website.</p>
				<p>(e)	The user of this website shall never send any kind of personal message to anyone associated with this website without the free consent of that individual or without a written consent by tabcii.com.</p>
				<p>(f)	The service user shall make the payment on time as per the agreement and shall not delay the same  unless the service provider has not completed his work or has damaged the property/goods or has done any professional misconduct or any typographical error is made in terms of the price fixed for a particular service or for the identity of the service provider.</p>
				<p>(g)	The service provider shall perform its services in accordance  with the agreement that has been executed unless the service user has not complied with his part of agreement or the service user refuses or fails to pay or a typographical error is made in regard to the identity of the service user etc. </p>
				<p>(h)	The service provider shall not cheat tabcii.com in providing with the correct and true status of delivery and payment received by it and shall make payments to tabcii.com as per the payment plan opted by it.</p>
				<p>(i)	The users of this website have a right to give their feedback in regard to the services availed by them through this website, however  they shall not use any unethical, foul or bad language while providing their feedback. If any such unethical, immoral or bad language is used while giving feedbacktabcii.com has a right to delete/erase such a comment/feedback and may also terminate the account of such user at its sole discretion without giving any notice.</p>
			</div>
			<div class="col-md-12">
				<h3 class="terms-use"> CONDITIONS FOR SERVICE PROVIDERS </h3>
				<p>The service providers shall not provide false or wrong 	information in regard to their profile or the offers which they give on this website. The service provider shall not provideany false information in relation to the services or offers being provided by them or pertaining to their location of service on the website</p>
				<p>The service providers shall not publish any offer list which has a link of a third party website or any other direct service provider contact information who can provide the services directly. Doing so shall be considered as  professional misconduct and such service provider shall be barred from using this website for ever.</p>
				<p>The service provider shall provide offers keeping in mind the legality of such offer and shall also keep in mind that the payment for the services provided shall be done only through the payment options available by this website.  </p>
				<p>If any of the mentioned conditions are not followed by any of the service providers  thentabcii.com has complete authority to cancel/erase the offers or any other content published by the service provider or terminate his account or forfeit any fees earned by the service provider on a cancelled offer.</p>
				<p>If a service provider places a bid and the bid is accepted then the service provider is legally bound to comply with that agreement and cannot refuse to do so unless an extraordinary circumstance occurs which makes it impossible for the service provider to complete the agreement. However,  for that, the service provider has to send a mail to tabcii.com and it shall be the sole discretion of tabcii.com to decide whether it is possible for the service provider or not to execute the agreement. If tabcii.com feels that it is not possible for the service provider  then the service provider shall be liable to pay for any loss incurred by tabcii.com in any manner and if tabcii.com feels that it is possible for the service provider to execute the agreement and still the service provider denies from doing so than the service provider shall be liable to pay for any loss incurred by tabcii.com in any manner and tabcii.com has the sole discretion to terminate the account of such service provider.</p>
				<p>The service provider shall make sure that the goods shall be delivered on time as promised by them and goodsshall be delivered safely and exactly in the state as were handed over to the service provider. It is upto the service provider to check the goods before he takes them in his possession to see the state of goods and also to check if the goods mentioned in the description matches with the goods given to him for delivery.</p>
				<p>If the customer/service user opts for the COD option for making the payment then the service provider shall make payment of tabcii.com’s share within a time period of 10 days from the date of receiving of the payment. </p>
				<p>If it is found that the goods handed over to the service provider for delivery were stolen and the guilt is proved on part of the service provider then not only will the present contract be terminated but also legal action will be taken against such service provider.</p>
				<h3 class="terms-use"> CONDITIONS FOR SERVICE USERS </h3>
				<p>The service users shall comply with the following things:
					(a) 	The service user shall pay for the services availed by them ;
					(b) 	The service user shall agree to avail the services of a service provider when the service useris well aware of all the terms and conditions of the service provider and agrees to accept all those terms.
				(c) 	The service user shall never misuse any service provided by tabcii.com  now or in future.</p>
				<p> If in case any service user is found in violation of any of the terms and conditions, then tabcii.com shall have the sole discretion to cancel any posting and terminate the account of such user.</p>
				<p>It is the responsibility of the service user that the description of the goods provided by the service user shall match with the actual goods handed over to the service provider and in case it does not match then the service provider is at liberty to not provide any services and inform tabcii.com of any such situation. If any kind of anti social goods or illegal goods are found to be there provided by the service user then its sole liability will be of the service user.tabcii.com shall not be held liable for any such thing.</p>
				<h3 class="terms-use">Refund Policy </h3>
				<p>tabcii.com believes in fair dealing and ensures to provide the best services  to our customers . If in case there is a cancellation of any order as per our cancellation policy for which payment has already been made through any of the online payment options available then the whole amount will be credited to the account of the customer from whom the payment was made after deducting non refundable booking charges and 3% transaction charges in processing the online transaction of the amount and/or any loss or expense incurred by tabcii.com or by the LSP. The amount shall be credited to the account from which the payment was made with in a period of 15 days from the date of cancellation of the order.</p>
				<h3 class="terms-use">Cancellation Policy </h3>
				<p>tabcii.com believes in providing its customer with the best service possible and we at tabcii.com try to make the usage of our website as simple as possible for our customers. In case our customer after placing an order wants to cancel the same then it shall be done as per the steps provided below which shall be different for different situations.</p>
				<p>If a customer has placed an order and received bids from different LSP’s and then if the customer does not respond to any bid with in a period of 48 hours, then the order of the customer will be automatically cancelled, </p>
				<p>
				If a customer has placed an order and received bids from different LSP’s and has also accepted one of the bids, then in the event of any cancellation ,the customer has to contact the customer care executive immediately and get their order cancelled andif in case there is any loss or expense incurred by tabcii.com or by the LSP chosen by the customer, then the customer shall be liable to pay for any such loss or expense and the same shall be deducted from the payment made by the customer and the  balance amount will be refunded to the customer’s account as per our refund policy,</p>
				<p>If a customer has placed an order and received bids from different LSP’s and has also accepted one of the bids and has opted for making the payment by COD (cash on delivery) mode, then in case of any cancellation, the customer has to contact the customer care executive immediately and get their order cancelled and if in case there is any loss or expense incurred by tabcii.com or by the LSP chosen by the customer,  the customer shall be liable to pay for such loss or expense and if the customer will not pay for the loss or expense, then tabcii.com has the liberty to take legal action against the customer to recover the losses or expenses incurred including the litigation charges.</p>
				<h3 class="terms-use">RIGHT TO REMOVE CONTENTS</h3>
				<p>The contents that are posted on  abc.con are the exclusive property of this website,  however tabcii.com does not take any guarantee of any other content posted by either any service user or any service provider.  tabcii.com has the exclusive and absolute right to decide on its sole discretion to either delete/erase/remove any of the content that is posted on its website at any point of time without giving any notice to the person who published that particular content.</p>
				<h3 class="terms-use">SUGGESTIONS</h3>
				<p>If any user of this website sends comments, questions or suggestions though letter, email, telephone, or otherwise, all such suggestions can be used by tabcii.comin any manner it may desire andthe person who is sending the suggestion gives  complete and absolute authority to tabcii.com to use such suggestions in any manner it may desire and the person sending such suggestion shall not have any right to claim any benefit for providing abc.con with such suggestion.</p>
				<h3 class="terms-use">RIGHT TO MODIFICATION AND TERMINATION</h3>
				<p>tabcii.com has the complete and absolute right and authority to modify or terminate temporarily or permanently, the services of this website with or without serving any notice to any user of this website at its sole discretion and tabcii.com shall not be liable for any loss suffered by any user of this website due to discontinuance of this website.</p>
				<p>tabcii.com has the complete/absolute right and consent by its users to delete/erase, terminate, or deactivate the accounts or block email Id’s of the users without giving any notice to them at its sole discretion if the user is found breaching the terms of use or any other policy of this website.</p>
				<p>The users also, in case they are not willing to continue association with us have the right to deactivate his account at his own will without sending any notice to us. But the termination of a user account does not make the user free from abiding with the privacy policy and other policies of this website which means that the users are not allowed to pass on any personal or professional information provided to the user by tabcii.com to anyone else and also the useragree to indemnify tabcii.com and its officers, managers, affiliates, successor, assigns, directors, agents, service professionals and employees harmless from any claim or demand, including reasonable litigation costs incurred by tabcii.com.</p>
				<h3 class="terms-use">INTELLECTUAL PROPERTY RIGHTS</h3>
				<p>The contents of this Website are the exclusive property of tabcii.com including the text and software and also all the other forms of content including trademarks and logos contained herein are owned by tabcii.com. Other trademarks, names and logos on this Website are the property of their respective owners.</p>
				<p>Data on the Website which may or may not be the property of tabcii.comshall not be used, copied, reproduced, circulated, transmitted, put on air, displayed, sold, licensed, or otherwise without the prior consent of tabcii.com. The user of this website agrees not to use, copy or distribute any of the Data other than as expressly permitted herein including any use, copying or distribution of submitted content obtained through the Website for any commercial purposes</p>
				<h3 class="terms-use">FEES CHARGED</h3>
				<p>The  XYZcompany charges booking fees from the customers. Other than that  tabcii.com charges fees only from the logistic service providers as per the agreement between tabcii.com and logistic service providers.  tabcii.com does not take any charges from the service users  however, it holds back the right to take fees/charges from the service users  in future if it desires.  If the service users require any documents that are to be supplied to them in hard copy then the service users have to pay a certain amount for that serviceaviled.
				</p>
				<h3 class="terms-use">BASIC PROVISIONS</h3>
				<p>tabcii.com is not a party to any service contract that takes place between the service provider and service user. Each registered user shall accept and agree to this fact that tabcii.com is not a party to any agreement that takes place between Registered service provider in connection with any Service offered and the registered service user. There is no such relation of agency, partnership, join venture, or employment between tabcii.com and any service provider or service user by way of any terms of use or any policy on this website. </p>
				<h3 class="terms-use">DISPUTE RESOLUTION</h3>
				<p>In case any dispute take place between tabcii.com and any user or between any service provider or service user then such a dispute shall be resolved by way of alternative dispute resolution procedures such as mediation or arbitration as alternatives to litigation. We at tabcii.com believe that any and every issue can be resolved if a proper initiative is taken for that purpose and thus only alternative dispute resolution shall be opted to resolve any issue/dispute.
				</p>
				<h3 class="terms-use">LAW</h3>
				<p>The Terms of Use shall be governed by the laws of India only and any legal proceeding arising out of this Agreement shall take place exclusively in the courts located in New Delhi, India.</p>
				<h3 class="terms-use">INDEMNIFICATION</h3>
				<p>The term user shall include the customer and the logistic service provider both. The users of this website accept to indemnify and keep  “tabcii.com” and its respective officers, directors, employee, successor and assign harmless from and against any and all liabilities, obligation, losses, damages, penalties, claims, demands, action, suits. Cost and expenses (including, without limitation, reasonable legal fees and expenses) arising from the claim of third parties of whatsoever kind or nature imposed on, incurred by or asserted against tabcii.com, resulting from, arising out of or incurred with respect to (i) the breach of any covenant or warranty made by  any user or a material breach of these policies, or (ii) the performance of the services by any user.
					tabcii.com has the absolute right to transfer or assign the terms of use and any rights and licenses granted hereunder, however no one else has  the right to do so without the written consent of tabcii.com.
				</p>
				<h3 class="terms-use">WARRANTY AND GUARANTEE</h3>
				<p>The user of this website agree to give their free consent to use this website at their own risk and in no circumstance can anyonethird party or the user of this website will hold liable in any way tabcii.com and itsmanagers, directors, employees, successors, assigns, subsidiaries, affiliates, service professionals, and agents for any loss or any problem faced by anyone. tabcii.com makes no warranties, representations, or guarantees in connection with this website, the services offered on this website, or any content relating to the quality, suitability, truth, accuracy or completeness of any information. We suggest you not to believe the information given on the website blindly as all information that is uploaded is not under the control of tabcii.com and it is not possible to check whetherthe data uploaded is true or not, thus we do not give any warranty or guarantee in this regard. The user of this website shall avail its services at its own risk as we neither take the guarantee for the customers nor for the service providers or for the information that is being provided by tabcii.com or by any third party on this website.</p>
				<h3 class="terms-use">LIMITATIONS OF LIABILITY</h3>
				<p>This is to ensure that in no circumstances tabcii.com or its respective managers, directors, employees, successors, assigns, subsidiaries, affiliates, service professionals, attorneys or agents, shall be liable to any user of this website for any direct or indirect  loss of business, revenue, profits or other economic loss caused from any use of this website or from any service provider of this website or from any customer of this website which means that in case any loss is suffered by the service provider professional because of the customer and if the customer suffers any loss due to any service provider professional or any loss is suffered by the customer or the service provider professional due to any technical defect in the website, inaccuracy of data available on the website, if any breach of security of data takes place by any third party website or person, or any kind of moral, immoral, emotional, financial, goodwill loss is suffered by any third party, customer or service provider professional then no one can hold tabcii.com or its respective managers, directors, employees, successors, assigns, subsidiaries, affiliates, service professionals, attorneys or agents liable. The foregoing limitation of liability shall apply to the fullest extent permitted by law.</p>
				<p>The user of this website do hereby agree that tabcii.com shall not be held liable for the above mentioned contents or the defamatory, offensive, or illegal conduct of any third party or service user or service provider and the risk of any loss or damage which might take place rests entirely with the user of this website. </p>
				<h3 class="terms-use">FORCE MAJEURE</h3>
				<p>Neither party shall be liable for delay or failure in service or in payment caused by revolution, insurrection, riot, war, act of the public enemy, national emergency, strike, flood, fire, act of good, or by any other cause, whether similar or dissimilar which is not within the control of the party.</p>
				<h3 class="terms-use">SEVERABILITY</h3>
				<p>The policy makers have kept in mind all the legal statutes and laws while preparing the terms of use and other policies mentioned on this website, however If any term or other provision of the policies are invalid, illegal or incapable of being enforced by any rule of law or public policy then all other terms and provision of this agreement will nevertheless remain in full force and effect.</p>
				<h3 class="terms-use">Notice</h3>
				<p>tabcii.com has the sole and complete right to make any changes in the terms of use or privacy policy or any other policy or document/information provided on this website whenever tabcii.com feel the need to do so in accordance  with the change in laws or change in the company’s business policy but we ensure all who will be using this website that if any changes are made in the policies in regard to this website, such information shall be provided to you by email or postings on the Website.</p>
				<h3 class="terms-use">THIRD PARTY BENEFICIARIES</h3>
				<p>The policies of this website is strictly restricted to those who are a party to this agreement which is made through these policies and nothing contained in this POLICY is intended to, nor shall it confer upon, any person or entity other than the parties hereto and their respective subsidiaries, successors and permitted assigns, any benefit, right or remedies under or by any reason of these policies.</p>
				<h3 class="terms-use">THIRD PARTY WEBSITE</h3>
				<p>tabcii.com may have links to other websites and there data might beseen on this website in the form of advertisement or any other thing. But tabcii.com shall not be held liable for any content/image/data shown on its website which does not belong to it as tabcii.com does not have any control on other websites or their content.</p>
			</div>
		</div>
	</div>
</div>
<?php include 'footer.php' ?>